/**
 * Single source of truth for page metadata and structured data.
 *
 * This exists for the same reason `lib/nav.ts` does. The site's SEO surface was
 * assembled route by route, and the result was measurably inconsistent: of 27
 * routes only 5 declared a canonical, **zero** declared a Twitter card, **zero**
 * declared `openGraph.images`, the root layout declared no icons, and
 * `/login` sat in the sitemap with no `noindex` — an authentication page
 * advertised for indexing. Five of those gaps are the shallow-merge semantics
 * of the Metadata API rather than an oversight: `openGraph` and `twitter` are
 * replaced wholesale by a descendant, never deep-merged, so a page that sets
 * `openGraph.title` alone silently drops the root's description, image and
 * card type.
 *
 * That is why `pageMetadata()` returns a **complete** `Metadata` object rather
 * than a partial patch. A page must be able to call it and get valid, complete
 * tags with no knowledge of what the root layout happens to declare.
 *
 * Length budgets are applied here and *enforced* by `tests/seo.test.ts` via
 * `seoIssues()`, not by logging at runtime. A console warning in a server
 * component fires during `next build` and then is never read; a failing test
 * stops the merge.
 */

import type { Metadata } from "next";

import { SITE, SITE_LOGO_PATH, SITE_URL, absoluteUrl } from "./site";
import type { BlogPost, College, Course, Exam, Faq, MockTest, Scholarship } from "./types";

/**
 * Google renders roughly 60 characters of title and 155–160 of description
 * before truncating. The budgets are slightly tighter than the render widths so
 * that the template suffix (` · padhaanewala`) cannot push a compliant title
 * over the edge.
 */
export const TITLE_MAX = 60;
export const DESCRIPTION_MAX = 155;

/** Generated by `app/opengraph-image.tsx`, so it cannot drift from the code. */
export const OG_IMAGE_PATH = "/opengraph-image";
export const OG_IMAGE_ALT = `${SITE.name} — ${SITE.tagline}`;

/**
 * Site-wide keywords, used as the fallback for any page that does not declare
 * its own. Moved here from `app/layout.tsx` so `pageMetadata()` and the root
 * layout cannot disagree about them.
 */
export const SITE_KEYWORDS = [
  "padhaanewala",
  "college discovery",
  "college search india",
  "compare colleges",
  "engineering colleges",
  "medical colleges",
  "mba colleges",
  "entrance exams",
  "mock tests",
  "scholarships",
];

export interface OgImage {
  url: string;
  width: number;
  height: number;
  alt: string;
}

export const DEFAULT_OG_IMAGE: OgImage = {
  url: absoluteUrl(OG_IMAGE_PATH),
  width: 1200,
  height: 630,
  alt: OG_IMAGE_ALT,
};

export function ogImage(alt: string): OgImage {
  return { ...DEFAULT_OG_IMAGE, alt };
}

/* ------------------------------------------------------------------ *
 * Text normalisation
 * ------------------------------------------------------------------ */

/**
 * Collapse HTML and whitespace so a value that came from a rich-text column is
 * safe to put in a meta tag.
 *
 * Angle brackets are stripped rather than escaped: a `<meta content>` attribute
 * is HTML-escaped by React on render, but a description that arrived as markup
 * ("<p>Best <b>colleges</b></p>") reads as noise in a search result, and
 * stripping it means the same text works as a JSON-LD `description` too, where
 * there is no escaping layer at all.
 */
export function plainText(input: string | null | undefined): string {
  if (!input) return "";
  return input
    .replace(/<[^>]*>/g, " ")
    .replace(/&nbsp;/gi, " ")
    .replace(/&amp;/gi, "&")
    .replace(/&lt;/gi, "<")
    .replace(/&gt;/gi, ">")
    .replace(/&quot;/gi, '"')
    .replace(/&#39;|&apos;/gi, "'")
    .replace(/\s+/g, " ")
    .trim();
}

/** Clamp on a word boundary, so a cut never leaves half a word behind. */
export function clamp(input: string, max: number): string {
  const text = plainText(input);
  if (text.length <= max) return text;
  const cut = text.slice(0, max - 1);
  const lastSpace = cut.lastIndexOf(" ");
  const body = lastSpace > max * 0.6 ? cut.slice(0, lastSpace) : cut;
  return `${body.replace(/[\s,;:.\-–—/|]+$/, "")}…`;
}

export function metaTitle(input: string): string {
  return clamp(input, TITLE_MAX);
}

export function metaDescription(input: string): string {
  return clamp(input, DESCRIPTION_MAX);
}

/* ------------------------------------------------------------------ *
 * pageMetadata
 * ------------------------------------------------------------------ */

export interface PageSeo {
  /** Page title, without the `%s · padhaanewala` template suffix. */
  title: string;
  /** Already-renderable text. HTML is stripped and the result clamped. */
  description: string;
  /** Canonical path. Query strings and hashes are never part of a canonical. */
  path: string;
  type?: "website" | "article";
  image?: OgImage;
  keywords?: string[];
  /** `article:published_time` and friends. Only read when `type` is article. */
  publishedTime?: string;
  authors?: string[];
  /** Excluded from the index but still followed, for links a reader needs. */
  noindex?: boolean;
  nofollow?: boolean;
}

export function canonicalFor(path: string): string {
  return absoluteUrl(path);
}

/**
 * The Twitter/X handle, without the `@`. Declared once because the same string
 * is used by the `twitter:site` tag and by the `sameAs` list on the
 * Organization node, and those two are exactly the kind of pair that drifts.
 */
export const SOCIAL_HANDLE = "padhaanewala";

export function pageMetadata(seo: PageSeo): Metadata {
  const canonical = canonicalFor(seo.path);
  const title = metaTitle(seo.title);
  const description = metaDescription(seo.description);
  const image = seo.image ?? DEFAULT_OG_IMAGE;
  const isArticle = seo.type === "article";

  return {
    title,
    description,
    alternates: { canonical },
    keywords: seo.keywords ?? SITE_KEYWORDS,
    robots: seo.noindex
      ? { index: false, follow: !seo.nofollow }
      : { index: true, follow: true },
    openGraph: {
      type: isArticle ? "article" : "website",
      locale: "en_IN",
      url: canonical,
      siteName: SITE.name,
      title,
      description,
      images: [image],
      ...(isArticle
        ? {
            publishedTime: seo.publishedTime,
            authors: seo.authors?.map((name) => ({ name })),
          }
        : {}),
    },
    twitter: {
      card: "summary_large_image",
      site: `@${SOCIAL_HANDLE}`,
      title,
      description,
      images: [image],
    },
  };
}

/* ------------------------------------------------------------------ *
 * seoIssues — the enforcement hook
 * ------------------------------------------------------------------ */

export interface SeoCheck {
  path: string;
  title: string;
  description: string;
  noindex?: boolean;
}

/**
 * Returns one message per defect. Empty array means the page is clean.
 *
 * Called by the test suite against the real route inventory. It exists so the
 * budgets are checked by something that fails a build rather than by a
 * `console.warn` nobody reads.
 */
export function seoIssues(page: SeoCheck): string[] {
  const issues: string[] = [];
  const title = plainText(page.title);
  const description = plainText(page.description);

  if (!title) issues.push(`${page.path}: empty title`);
  if (title.length > TITLE_MAX) {
    issues.push(`${page.path}: title is ${title.length} chars (max ${TITLE_MAX}) — "${title}"`);
  }
  if (!description) issues.push(`${page.path}: empty description`);
  if (description.length > DESCRIPTION_MAX) {
    issues.push(
      `${page.path}: description is ${description.length} chars (max ${DESCRIPTION_MAX})`,
    );
  }
  if (!page.path.startsWith("/")) {
    issues.push(`${page.path}: canonical path must start with "/"`);
  }
  return issues;
}

/* ------------------------------------------------------------------ *
 * Structured data
 * ------------------------------------------------------------------ */

export type JsonLdNode = Record<string, unknown>;

/**
 * A `@graph` wrapper, which is how multiple nodes on one page should be
 * expressed. Emitting several sibling `<script type="application/ld+json">`
 * blocks is legal but fragments the entity graph: a crawler reading one block
 * has no `sameAs` or `mainEntity` edge to the block beside it.
 *
 * `null` is accepted because `breadcrumbLd()` and `faqPageLd()` return null
 * when there is nothing to declare, and a caller must not have to special-case
 * that at every call site — the filter below is what drops it. The
 * `Node | null` entry type is a widening of the declared contract, not a
 * change to it: the return type is still a non-null graph.
 */
export function ldGraph(nodes: (JsonLdNode | null | undefined)[]): JsonLdNode {
  return { "@context": "https://schema.org", "@graph": nodes.filter(Boolean) };
}

export function organizationLd(): JsonLdNode {
  return {
    "@type": "Organization",
    "@id": `${SITE_URL}/#organization`,
    name: SITE.name,
    legalName: SITE.legalName,
    url: SITE_URL,
    description: SITE.description,
    foundingDate: String(SITE.foundedYear),
    logo: {
      "@type": "ImageObject",
      url: absoluteUrl(SITE_LOGO_PATH),
    },
    email: SITE.email,
    telephone: SITE.phone,
    address: {
      "@type": "PostalAddress",
      streetAddress: SITE.address.street,
      addressLocality: SITE.address.locality,
      addressRegion: SITE.address.region,
      postalCode: SITE.address.postalCode,
      addressCountry: SITE.address.country,
    },
    sameAs: Object.values(SITE.social),
  };
}

export function webSiteLd(): JsonLdNode {
  return {
    "@type": "WebSite",
    "@id": `${SITE_URL}/#website`,
    url: SITE_URL,
    name: SITE.name,
    description: SITE.description,
    inLanguage: "en-IN",
    publisher: { "@id": `${SITE_URL}/#organization` },
  };
}

export interface Crumb {
  name: string;
  path: string;
}

/**
 * Breadcrumbs are emitted on every page except the home page, which has no
 * trail. A `BreadcrumbList` must include the page it describes as its last
 * item and the home page as its first, otherwise the two ends do not line up
 * with the visible trail.
 */
export function breadcrumbLd(trail: Crumb[]): JsonLdNode | null {
  if (trail.length < 2) return null;
  return {
    "@type": "BreadcrumbList",
    itemListElement: trail.map((crumb, index) => ({
      "@type": "ListItem",
      position: index + 1,
      name: crumb.name,
      item: canonicalFor(crumb.path),
    })),
  };
}

export function blogPostingLd(post: BlogPost): JsonLdNode {
  const url = canonicalFor(`/blog/${post.slug}`);
  return {
    "@type": "BlogPosting",
    "@id": `${url}#article`,
    headline: metaTitle(post.title),
    description: metaDescription(post.excerpt),
    url,
    mainEntityOfPage: { "@type": "WebPage", "@id": url },
    datePublished: post.date,
    dateModified: post.date,
    author: { "@type": "Person", name: post.author },
    publisher: { "@id": `${SITE_URL}/#organization` },
    inLanguage: "en-IN",
    keywords: post.tags?.join(", "),
    articleSection: post.category,
    isAccessibleForFree: true,
  };
}

export function itemListLd(items: { name: string; path: string }[], name: string): JsonLdNode {
  return {
    "@type": "ItemList",
    name,
    numberOfItems: items.length,
    itemListElement: items.map((item, index) => ({
      "@type": "ListItem",
      position: index + 1,
      name: item.name,
      url: canonicalFor(item.path),
    })),
  };
}

/**
 * `FAQPage` is only emitted where the questions are genuinely on the page as
 * question-and-answer pairs. Marking up FAQs that are not visible is a manual
 * action against Google's structured-data guidelines.
 */
export function faqPageLd(faqs: Faq[]): JsonLdNode | null {
  if (!faqs.length) return null;
  return {
    "@type": "FAQPage",
    mainEntity: faqs.map((faq) => ({
      "@type": "Question",
      name: plainText(faq.q),
      acceptedAnswer: { "@type": "Answer", text: plainText(faq.a) },
    })),
  };
}

export function courseLd(course: Course, path: string): JsonLdNode {
  return {
    "@type": "Course",
    name: course.name,
    description: plainText(course.specialization) || undefined,
    url: canonicalFor(path),
    provider: { "@id": `${SITE_URL}/#organization` },
    ...(course.duration ? { timeRequired: course.duration } : {}),
  };
}

/**
 * `EducationalOccupationalCredential` would be the accurate type for an exam
 * paper, but it models a credential that has been *conferred*. `Course` is the
 * type Google accepts for an exam or test being offered, which is what a mock
 * test is.
 */
export function mockTestLd(test: MockTest): JsonLdNode {
  const url = canonicalFor(`/mock-tests/${test.slug}`);
  return {
    "@type": "Course",
    name: test.title,
    description: metaDescription(test.description),
    url,
    provider: { "@id": `${SITE_URL}/#organization` },
    educationalLevel: test.exam,
    inLanguage: "en-IN",
    ...(test.topics?.length ? { about: test.topics.join(", ") } : {}),
    isAccessibleForFree: true,
    offers: {
      "@type": "Offer",
      price: "0",
      priceCurrency: "INR",
      availability: "https://schema.org/InStock",
      url,
    },
  };
}

/**
 * An exam is an `EducationEvent`: it has a start date, a location and a mode of
 * attendance, all of which `Event` models. `startDate` is only emitted when a
 * date is actually published — an unparsed or tentative string is worse than
 * none, and a wrong one is a rich-result penalty.
 */
export function eventLd(exam: Exam): JsonLdNode {
  const dated = exam.dates?.find((d) => !d.tentative && isIsoDate(d.date));
  return {
    "@type": "EducationEvent",
    name: exam.name,
    description: metaDescription(exam.overview),
    url: canonicalFor(`/exams/${exam.slug}`),
    startDate: dated ? toIsoDate(dated.date) : undefined,
    eventStatus: "https://schema.org/EventScheduled",
    eventAttendanceMode: "https://schema.org/OfflineEventAttendanceMode",
    location: {
      "@type": "Place",
      address: {
        "@type": "PostalAddress",
        addressCountry: "IN",
      },
    },
    organizer: { "@id": `${SITE_URL}/#organization` },
    ...(exam.website ? { url: exam.website } : {}),
  };
}

export function scholarshipLd(scholarship: Scholarship): JsonLdNode {
  const url = canonicalFor(`/scholarships`);
  return {
    "@type": "Grant",
    name: scholarship.name,
    description: metaDescription(
      `${scholarship.provider} scholarship for ${scholarship.eligibility}. ${scholarship.amount}.`,
    ),
    url,
    funder: { "@id": `${SITE_URL}/#organization` },
  };
}

/**
 * Moved here from `app/colleges/[slug]/page.tsx`, where it was inline and
 * untestable. The rating and offer-catalog branches are conditional for a
 * reason: a `CollegeOrUniversity` node carrying `aggregateRating` with a
 * review count of zero is a rich-result violation, and one carrying an empty
 * `hasOfferCatalog` is meaningless markup.
 */
export function collegeLd(college: College): JsonLdNode {
  const url = canonicalFor(`/colleges/${college.slug}`);
  const node: JsonLdNode = {
    "@type": "CollegeOrUniversity",
    "@id": `${url}#college`,
    name: college.name,
    url,
    description: metaDescription(college.tagline || college.overview),
    ...(college.founded ? { foundingDate: String(college.founded) } : {}),
    address: {
      "@type": "PostalAddress",
      addressLocality: college.city,
      addressRegion: college.state,
      postalCode: college.pincode,
      addressCountry: "IN",
    },
  };

  if (college.rating > 0 && college.reviewCount > 0) {
    node.aggregateRating = {
      "@type": "AggregateRating",
      ratingValue: college.rating,
      reviewCount: college.reviewCount,
    };
  }

  const courses = college.courses?.slice(0, 20) ?? [];
  if (courses.length) {
    node.hasOfferCatalog = {
      "@type": "OfferCatalog",
      name: `Courses at ${college.name}`,
      itemListElement: courses.map((course, index) => ({
        "@type": "Course",
        position: index + 1,
        name: course.name,
        url: canonicalFor(`/colleges/${college.slug}`),
      })),
    };
  }

  return node;
}

/* ------------------------------------------------------------------ *
 * Date helpers
 * ------------------------------------------------------------------ */

const ISO_DATE = /^\d{4}-\d{2}-\d{2}/;

export function isIsoDate(value: string | undefined | null): boolean {
  return Boolean(value && ISO_DATE.test(value.trim()));
}

/**
 * Only widen a date that is already ISO. A value like "Expected March 2026" is
 * passed through unchanged, and the caller is expected to have decided that is
 * good enough; converting it here would be inventing a day.
 */
export function toIsoDate(value: string): string {
  const trimmed = value.trim();
  return ISO_DATE.test(trimmed) ? trimmed : value;
}
