"""add mock tests and questions

Revision ID: 4e7270c87f0c
Revises: 63603ea2106d
Create Date: 2026-09-11 02:07:07.487605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e7270c87f0c'
down_revision: Union[str, Sequence[str], None] = '63603ea2106d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mock_tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=100), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('question_type', sa.String(length=20), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('total_marks', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('negative_marking', sa.Boolean(), nullable=False),
    sa.Column('negative_marks_value', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('attempts_allowed', sa.Integer(), nullable=False),
    sa.Column('question_randomization', sa.Boolean(), nullable=False),
    sa.Column('option_randomization', sa.Boolean(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('result_visibility', sa.String(length=20), nullable=False),
    sa.Column('test_type', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mock_tests_course_id'), 'mock_tests', ['course_id'], unique=False)
    op.create_index(op.f('ix_mock_tests_difficulty'), 'mock_tests', ['difficulty'], unique=False)
    op.create_index(op.f('ix_mock_tests_exam_id'), 'mock_tests', ['exam_id'], unique=False)
    op.create_index(op.f('ix_mock_tests_name'), 'mock_tests', ['name'], unique=False)
    op.create_index(op.f('ix_mock_tests_slug'), 'mock_tests', ['slug'], unique=True)
    op.create_index(op.f('ix_mock_tests_subject'), 'mock_tests', ['subject'], unique=False)
    op.create_index(op.f('ix_mock_tests_test_type'), 'mock_tests', ['test_type'], unique=False)
    op.create_table('test_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mock_test_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(length=20), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('correct_answer', sa.String(length=255), nullable=True),
    sa.Column('marks', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('negative_marks', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mock_test_id'], ['mock_tests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_questions_mock_test_id'), 'test_questions', ['mock_test_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_questions_mock_test_id'), table_name='test_questions')
    op.drop_table('test_questions')
    op.drop_index(op.f('ix_mock_tests_test_type'), table_name='mock_tests')
    op.drop_index(op.f('ix_mock_tests_subject'), table_name='mock_tests')
    op.drop_index(op.f('ix_mock_tests_slug'), table_name='mock_tests')
    op.drop_index(op.f('ix_mock_tests_name'), table_name='mock_tests')
    op.drop_index(op.f('ix_mock_tests_exam_id'), table_name='mock_tests')
    op.drop_index(op.f('ix_mock_tests_difficulty'), table_name='mock_tests')
    op.drop_index(op.f('ix_mock_tests_course_id'), table_name='mock_tests')
    op.drop_table('mock_tests')
    # ### end Alembic commands ###