"""add scholarships and exams

Revision ID: 63603ea2106d
Revises: 459f3e0774ed
Create Date: 2026-09-11 01:58:17.294912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63603ea2106d'
down_revision: Union[str, Sequence[str], None] = '459f3e0774ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('conducting_authority', sa.String(length=255), nullable=False),
    sa.Column('exam_type', sa.String(length=50), nullable=False),
    sa.Column('eligibility', sa.Text(), nullable=True),
    sa.Column('application_start_date', sa.Date(), nullable=True),
    sa.Column('application_deadline', sa.Date(), nullable=True),
    sa.Column('exam_date', sa.Date(), nullable=True),
    sa.Column('admit_card_date', sa.Date(), nullable=True),
    sa.Column('result_date', sa.Date(), nullable=True),
    sa.Column('official_website', sa.String(length=255), nullable=True),
    sa.Column('official_notification', sa.String(length=255), nullable=True),
    sa.Column('syllabus', sa.JSON(), nullable=True),
    sa.Column('faqs', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exams_application_deadline'), 'exams', ['application_deadline'], unique=False)
    op.create_index(op.f('ix_exams_conducting_authority'), 'exams', ['conducting_authority'], unique=False)
    op.create_index(op.f('ix_exams_exam_type'), 'exams', ['exam_type'], unique=False)
    op.create_index(op.f('ix_exams_name'), 'exams', ['name'], unique=False)
    op.create_index(op.f('ix_exams_slug'), 'exams', ['slug'], unique=True)
    op.create_table('scholarships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=255), nullable=False),
    sa.Column('ownership', sa.String(length=20), nullable=False),
    sa.Column('eligibility', sa.Text(), nullable=True),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.Column('course', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('income_criteria', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.String(length=255), nullable=True),
    sa.Column('application_deadline', sa.Date(), nullable=True),
    sa.Column('documents_required', sa.JSON(), nullable=True),
    sa.Column('application_procedure', sa.Text(), nullable=True),
    sa.Column('official_website', sa.String(length=255), nullable=True),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('last_verified_date', sa.Date(), nullable=True),
    sa.Column('next_verification_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scholarships_application_deadline'), 'scholarships', ['application_deadline'], unique=False)
    op.create_index(op.f('ix_scholarships_category'), 'scholarships', ['category'], unique=False)
    op.create_index(op.f('ix_scholarships_name'), 'scholarships', ['name'], unique=False)
    op.create_index(op.f('ix_scholarships_provider'), 'scholarships', ['provider'], unique=False)
    op.create_index(op.f('ix_scholarships_slug'), 'scholarships', ['slug'], unique=True)
    op.create_index(op.f('ix_scholarships_state_id'), 'scholarships', ['state_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scholarships_state_id'), table_name='scholarships')
    op.drop_index(op.f('ix_scholarships_slug'), table_name='scholarships')
    op.drop_index(op.f('ix_scholarships_provider'), table_name='scholarships')
    op.drop_index(op.f('ix_scholarships_name'), table_name='scholarships')
    op.drop_index(op.f('ix_scholarships_category'), table_name='scholarships')
    op.drop_index(op.f('ix_scholarships_application_deadline'), table_name='scholarships')
    op.drop_table('scholarships')
    op.drop_index(op.f('ix_exams_slug'), table_name='exams')
    op.drop_index(op.f('ix_exams_name'), table_name='exams')
    op.drop_index(op.f('ix_exams_exam_type'), table_name='exams')
    op.drop_index(op.f('ix_exams_conducting_authority'), table_name='exams')
    op.drop_index(op.f('ix_exams_application_deadline'), table_name='exams')
    op.drop_table('exams')
    # ### end Alembic commands ###