"""create_locations_universities_colleges_courses

Revision ID: 926c62eec261
Revises: 8422ac618df6
Create Date: 2026-09-11 01:45:37.159661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '926c62eec261'
down_revision: Union[str, Sequence[str], None] = '8422ac618df6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('degree', sa.String(length=100), nullable=True),
    sa.Column('duration', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('eligibility', sa.Text(), nullable=True),
    sa.Column('career_information', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_category'), 'courses', ['category'], unique=False)
    op.create_index(op.f('ix_courses_name'), 'courses', ['name'], unique=False)
    op.create_index(op.f('ix_courses_slug'), 'courses', ['slug'], unique=True)
    op.create_table('states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('is_union_territory', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_states_code'), 'states', ['code'], unique=True)
    op.create_index(op.f('ix_states_name'), 'states', ['name'], unique=True)
    op.create_table('districts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('state_id', 'name', name='uq_district_state_name')
    )
    op.create_index(op.f('ix_districts_code'), 'districts', ['code'], unique=False)
    op.create_index(op.f('ix_districts_name'), 'districts', ['name'], unique=False)
    op.create_index(op.f('ix_districts_state_id'), 'districts', ['state_id'], unique=False)
    op.create_table('universities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('is_deemed', sa.Boolean(), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_universities_name'), 'universities', ['name'], unique=True)
    op.create_index(op.f('ix_universities_slug'), 'universities', ['slug'], unique=True)
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('is_metropolitan', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cities_district_id'), 'cities', ['district_id'], unique=False)
    op.create_index(op.f('ix_cities_name'), 'cities', ['name'], unique=False)
    op.create_table('colleges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('college_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('official_name', sa.String(length=255), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('college_type', sa.String(length=50), nullable=True),
    sa.Column('ownership', sa.String(length=50), nullable=True),
    sa.Column('university_id', sa.Integer(), nullable=True),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('lat', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('lng', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('established_year', sa.Integer(), nullable=True),
    sa.Column('accreditation_naac', sa.String(length=20), nullable=True),
    sa.Column('accreditation_nba', sa.Boolean(), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('facilities', sa.JSON(), nullable=True),
    sa.Column('has_hostel', sa.Boolean(), nullable=True),
    sa.Column('hostel_facilities', sa.JSON(), nullable=True),
    sa.Column('total_reviews', sa.Integer(), nullable=False),
    sa.Column('average_rating', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('last_verified_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_colleges_college_id'), 'colleges', ['college_id'], unique=True)
    op.create_index(op.f('ix_colleges_name'), 'colleges', ['name'], unique=False)
    op.create_index(op.f('ix_colleges_slug'), 'colleges', ['slug'], unique=True)
    op.create_table('college_courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('college_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('annual_fee', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total_fee', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('intake_seats', sa.Integer(), nullable=True),
    sa.Column('admission_mode', sa.String(length=50), nullable=True),
    sa.Column('entrance_exam', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('college_id', 'course_id', name='uq_college_course')
    )
    op.create_index(op.f('ix_college_courses_college_id'), 'college_courses', ['college_id'], unique=False)
    op.create_index(op.f('ix_college_courses_course_id'), 'college_courses', ['course_id'], unique=False)
    op.create_table('admissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('college_course_id', sa.Integer(), nullable=False),
    sa.Column('admission_information', sa.Text(), nullable=True),
    sa.Column('eligibility_details', sa.Text(), nullable=True),
    sa.Column('entrance_exam', sa.String(length=100), nullable=True),
    sa.Column('application_start_date', sa.Date(), nullable=True),
    sa.Column('application_end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['college_course_id'], ['college_courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admissions_college_course_id'), 'admissions', ['college_course_id'], unique=False)
    op.create_table('fees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('college_course_id', sa.Integer(), nullable=False),
    sa.Column('tuition_fee', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('hostel_fee', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('examination_fee', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('other_charges', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total_approximate', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('fee_period', sa.String(length=50), nullable=True),
    sa.Column('academic_year', sa.String(length=20), nullable=False),
    sa.Column('is_approximate', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['college_course_id'], ['college_courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('college_course_id', 'academic_year', name='uq_fee_college_course_year')
    )
    op.create_index(op.f('ix_fees_academic_year'), 'fees', ['academic_year'], unique=False)
    op.create_index(op.f('ix_fees_college_course_id'), 'fees', ['college_course_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fees_college_course_id'), table_name='fees')
    op.drop_index(op.f('ix_fees_academic_year'), table_name='fees')
    op.drop_table('fees')
    op.drop_index(op.f('ix_admissions_college_course_id'), table_name='admissions')
    op.drop_table('admissions')
    op.drop_index(op.f('ix_college_courses_course_id'), table_name='college_courses')
    op.drop_index(op.f('ix_college_courses_college_id'), table_name='college_courses')
    op.drop_table('college_courses')
    op.drop_index(op.f('ix_colleges_slug'), table_name='colleges')
    op.drop_index(op.f('ix_colleges_name'), table_name='colleges')
    op.drop_index(op.f('ix_colleges_college_id'), table_name='colleges')
    op.drop_table('colleges')
    op.drop_index(op.f('ix_cities_name'), table_name='cities')
    op.drop_index(op.f('ix_cities_district_id'), table_name='cities')
    op.drop_table('cities')
    op.drop_index(op.f('ix_universities_slug'), table_name='universities')
    op.drop_index(op.f('ix_universities_name'), table_name='universities')
    op.drop_table('universities')
    op.drop_index(op.f('ix_districts_state_id'), table_name='districts')
    op.drop_index(op.f('ix_districts_name'), table_name='districts')
    op.drop_index(op.f('ix_districts_code'), table_name='districts')
    op.drop_table('districts')
    op.drop_index(op.f('ix_states_name'), table_name='states')
    op.drop_index(op.f('ix_states_code'), table_name='states')
    op.drop_table('states')
    op.drop_index(op.f('ix_courses_slug'), table_name='courses')
    op.drop_index(op.f('ix_courses_name'), table_name='courses')
    op.drop_index(op.f('ix_courses_category'), table_name='courses')
    op.drop_table('courses')
    # ### end Alembic commands ###
