"use client";

import { ArrowUpRight } from "lucide-react";
import { Panel } from "@/components/admin/primitives";

/**
 * SEO has no data source.
 *
 * This screen previously reported six invented audit scores (title tags 96,
 * meta descriptions 88, heading hierarchy 100, image alt text 74, structured
 * data 92, canonical URLs 85) alongside "Crawl errors 0", "Indexed pages 142
 * (+6)", "Backlinks 1.2K (+4.2%)" and "Avg. Core Web Vitals 0.9s (Pass)".
 *
 * None of it was measured. No crawler runs, no Search Console account is
 * connected, no analytics provider reports Core Web Vitals, and no backlink
 * source is polled — so every figure above was a constant, not an observation,
 * and it would have looked identical on a site with no pages indexed at all.
 * This is the last panel in the admin console that asserted invented numbers
 * as fact, so it now says what is missing instead.
 *
 * Two things below *are* real and are checked against the repo rather than
 * hardcoded: `app/robots.ts` and `app/sitemap.ts` both exist and are served by
 * Next.js. The route counts are transcribed from those files, so if either
 * changes this panel has to change with it.
 *
 * To make the scorecard real, the order is: crawl the site, or connect Search
 * Console and a field-data provider, store the results, expose an aggregate
 * endpoint, then render whatever that endpoint returns.
 */

/** Fixed routes emitted by `app/sitemap.ts` (17) plus the 6 `LEGAL_NAV` docs. */
const FIXED_SITEMAP_ROUTES = 23;

const ENDPOINTS = [
  {
    label: "robots.txt",
    href: "/robots.txt",
    note: "Generated by app/robots.ts — allows /, disallows /dashboard, /admin, /api/ and points at the sitemap.",
  },
  {
    label: "sitemap.xml",
    href: "/sitemap.xml",
    note: `Generated by app/sitemap.ts — ${FIXED_SITEMAP_ROUTES} fixed routes, plus one entry per college, course, exam, blog post and mock test resolved at request time.`,
  },
] as const;

export function SeoSection() {
  return (
    <div className="space-y-5">
      <Panel title="SEO audit" description="On-page checks, indexation and performance">
        <div className="py-6 text-center">
          <p className="text-sm font-semibold text-slate-700">No SEO data source is connected.</p>
          <p className="mx-auto mt-2 max-w-lg text-xs leading-relaxed text-slate-500">
            Nothing in this project crawls the site, reads Search Console, polls backlinks or measures
            Core Web Vitals, so there is no data behind crawl errors, index counts, audit scores or
            performance figures. Rather than show invented numbers, this panel stays empty. Connect a
            crawler or Search Console, store the results, and the scores can be rendered from real
            measurements.
          </p>
        </div>
      </Panel>

      <Panel title="Sitemap & robots" description="Endpoints served by this app">
        <ul className="space-y-3">
          {ENDPOINTS.map((endpoint) => (
            <li key={endpoint.href}>
              <a
                href={endpoint.href}
                target="_blank"
                rel="noreferrer"
                className="group flex items-start gap-3 rounded-xl bg-slate-50 px-4 py-3 transition hover:bg-slate-100 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-purple-500"
              >
                <span className="min-w-0 flex-1">
                  <span className="flex items-center gap-1 text-sm font-medium text-gray-700">
                    {endpoint.label}
                    <ArrowUpRight
                      aria-hidden="true"
                      className="h-3.5 w-3.5 text-slate-400 transition group-hover:text-purple-600"
                    />
                  </span>
                  <span className="mt-1 block text-xs leading-relaxed text-slate-500">
                    {endpoint.note}
                  </span>
                </span>
              </a>
            </li>
          ))}
        </ul>
      </Panel>
    </div>
  );
}
